#!/bin/sh
EMMC="$(ls /dev/mmcblk* | grep -F boot0 | sed 's/boot0//')"
BOOTDEV="$(readlink -f /dev/disk/by-partlabel/RROOT | grep -oE '/dev/mmcblk.')"
SD_EXT="$(ls /dev/mmcblk? | grep -v $BOOTDEV | grep -v $EMMC | head -n1)"

PART_BEGIN="$(parted -s $BOOTDEV print free | grep 'Free Space' | tail -n1 | awk '{print $1}')"
parted -s "$BOOTDEV" mkpart RDATA ext4 $PART_BEGIN '100%'
DATAPART="$BOOTDEV"p2

echo $DATAPART > /tmp/datapart
